### ISSUE TITLE
Error on Default Page Setup

### ISSUE THREAD

**Issue by alexpeasleyghc** [empira/PDFsharp.Samples#1]
Hello, I'm trying to update my project to the Net6.0 version. It is going pretty well. I ran into in a couple of spots. 

The lines in question:
document.DefaultPageSetup.Orientation = Orientation.Portrait;
document.DefaultPageSetup.BottomMargin = Unit.FromCentimeter(4);

The error:
'DefaultPageSetup must not be changed.'

Should my code be changed? Or is this a bug?

**Comment by TH-Soft** [comment]
It was always bad style to change the `DefaultPageSetup`. Now you get an error.

Assign a `Clone()` of the `DefaultPageSetup` to the `PageSetup` of your section and make the changes you need.
