### ISSUE TITLE
Not able to find pdfsharp.pdf.signature

### ISSUE THREAD

**Issue by niraj126** [empira/PDFsharp.Samples#8]
Hi,

I downloaded pdfsharp from nuget package, but it doesn't have pdfsharp.pdf.signature, I want to digitally sign pdf document, please help me how can I solve it.
Thanks in advance.

**Comment by TH-Soft** [comment]
There are no NuGet packages for the samples.
Did you get PDFsharp 6.2.0 Preview 1?

**Comment by niraj126** [comment]
Actually I am new, How can I get this version which contains signature?

**Comment by TH-Soft** [comment]
Enable downloading of prereleases and download it.

https://www.nuget.org/packages/PDFsharp-MigraDoc/6.2.0-preview-1

**Comment by niraj126** [comment]
@TH-Soft Thank you
